---
- hosts: bigbrother
  sudo: true
  remote_user: douglas
  roles:
    - role: stevenharradine/ansible-hostname
      hostname: big-brother
  tasks:
  - name: install software | apt
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - htop
      - git
      - nodejs
      - npm
      - apache2
      - php5
      - mysql-server
      - python-mysqldb
      - php5-mysql
      - libapache2-mod-php5
